# Generated by Django 5.2.5 on 2025-08-30 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_text', models.TextField(help_text='Text extracted from the document.')),
                ('summary', models.TextField(blank=True, help_text='AI-generated summary.', null=True)),
                ('top_words', models.JSONField(blank=True, help_text='Fallback top 5 most frequent words.', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='documents.document')),
            ],
        ),
    ]
